### ISSUE TITLE
Improve the format of the emails being sent

### ISSUE THREAD

**Issue by securedirective** [Alofoxx/club-websystem#10]
* Make the subject line unique for each email, so Gmail won't group them all together.
* Use the reply-to header, so replies will go to the user instead of to the club's gmail.

**Comment by Alofoxx** [comment]
emails should be sent using a managed framework. this will make them more accessible and less spam looking. 

there are a few good open source project to help send  emails that conform to standards

**Comment by securedirective** [comment]
I'll consider it. What do you have in mind?

**Comment by securedirective** [comment]
Look into using django-mailer for our email backend, so emails can be batched periodically instead of on demand.

Also find (or create) a email sending framework, so we aren't constantly maintaining HTML and TXT versions of each email template.

**Comment by securedirective** [comment]
Original issue fixed by commit 402d370257. We'll open a separate to-do item for using a mailer framework.
