### ISSUE TITLE
FullCalendar plugin should only be editable by officers

### ISSUE THREAD

**Issue by securedirective** [Alofoxx/club-websystem#6]
Look into using the built-in permissions for this.

**Comment by Alofoxx** [comment]
this will utilize the permission system. and editing the events should be its own page in a menu

**Comment by securedirective** [comment]
I'd like to utilize FullCalendar's editing features for simple edits, like shifting the next club meeting by an hour. We'll have a more full-featured editing page that will handle recurring events, etc.
