### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Alofoxx** [Alofoxx/club-websystem#8]
When running this project with manage.py runserver it runs my server out of memory, even after i bumped it to 4 gigs.

**Comment by securedirective** [comment]
Is this happening even without you loading any of the pages?

I've been running mine on a Manjaro VM with 768 MB of RAM, without any issues.

**Comment by securedirective** [comment]
Nope. I watched the memory usage reported by `top`, while I repeatedly refreshed the webpage. Yet I don't see any significant memory usage.

I'm going to assign this issue to you, Patrick, to see if you can narrow it down to a section of the code that's causing the problem. I cannot repeat the problem on my end.

**Comment by securedirective** [comment]
No problem on production server. Closing issue, unless we see it again.
